# DTS App Build & Health Check
name: DTS App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for backup files
      run: |
        echo "Checking for backup files that could cause conflicts..."
        find . -name "*.bak*" -o -name "*_backup_*" -o -name "*.swift.bak*" | tee duplicate_files.log
        if [ -s duplicate_files.log ]; then
          echo "⚠️ Warning: Found potential backup files that could cause build conflicts"
          cat duplicate_files.log
          exit 1
        else
          echo "✅ No problematic backup files found"
        fi
    
    - name: Check project structure
      run: |
        echo "Checking DTS App project structure..."
        
        # Check for main app files
        MAIN_APP="DTS App/DTS App/DTSApp.swift"
        if [ -f "$MAIN_APP" ]; then
          echo "✅ Main app entry point found: DTSApp.swift"
        else
          echo "❌ Error: DTSApp.swift not found"
          exit 1
        fi
        
        # Check for MainContentView (replaces ContentView)
        MAIN_CONTENT="DTS App/DTS App/MainContentView.swift"
        if [ -f "$MAIN_CONTENT" ]; then
          echo "✅ Main content view found: MainContentView.swift"
        else
          echo "❌ Error: MainContentView.swift not found"
          exit 1
        fi
        
        # Check for Jobber integration
        JOBBER_API="DTS App/DTS App/Managers/JobberAPI.swift"
        if [ -f "$JOBBER_API" ]; then
          echo "✅ Jobber API integration found"
        else
          echo "⚠️ Warning: Jobber API integration not found"
        fi
        
        # Check for loading screen
        LOADING_SCREEN="DTS App/DTS App/Views/LoadingScreenView.swift"
        if [ -f "$LOADING_SCREEN" ]; then
          echo "✅ Custom loading screen found"
        else
          echo "⚠️ Warning: Loading screen not found"
        fi
        
        echo "✅ Project structure validation complete"
    
    - name: Validate Swift files
      run: |
        echo "Validating Swift files for basic syntax..."
        find "DTS App/" -name "*.swift" -exec echo "Checking: {}" \;
        
        # Count total Swift files
        SWIFT_COUNT=$(find "DTS App/" -name "*.swift" | wc -l)
        echo "Found $SWIFT_COUNT Swift files"
        
        if [ "$SWIFT_COUNT" -lt 5 ]; then
          echo "⚠️ Warning: Only $SWIFT_COUNT Swift files found - project may be incomplete"
        else
          echo "✅ Project contains $SWIFT_COUNT Swift files"
        fi
